Window.SetBackgroundTopColor(0.024, 0.063, 0.188);
Window.SetBackgroundBottomColor(0.102, 0.294, 0.631);

logo.image = Image("logo.png");
logo.sprite = Sprite(logo.image);
logo.sprite.SetX(Window.GetX() + Window.GetWidth() / 2 - logo.image.GetWidth() / 2);
logo.sprite.SetY(Window.GetY() + Window.GetHeight() / 2 - logo.image.GetHeight() / 2 - 30);

bar.original_image = Image("bar.png");
bar.sprite = Sprite();
bar.x = Window.GetX() + Window.GetWidth() / 2 - bar.original_image.GetWidth() / 2;
bar.y = Window.GetY() + Window.GetHeight() / 2 + 60;
bar.sprite.SetX(bar.x);
bar.sprite.SetY(bar.y);

fun progress_callback(duration, progress) {
  bar.image = bar.original_image.Scale(bar.original_image.GetWidth() * progress, bar.original_image.GetHeight());
  bar.sprite.SetImage(bar.image);
}
Plymouth.SetBootProgressFunction(progress_callback);
